title: 'Landscape & Botany'
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.587940061930567
  brandStrength: 0.5665894271805882
  lightness: 0.7739676956553012
  brandColors:
    - '#3B2D0A'
    - '#7D083D'
    - '#BA3971'
    - '#CB9847'
    - '#FFFFC1'
  rhythmicContrast: 0.7062413892708719
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: alicissimo
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.6102295848540962
layout_spectrum: 0.4683665807824582
