name: alicissimo
favicon: null
layout_spectrum: 1
typography_spectrum: 0.6102295848540962
title: 'Landscape & Botany'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.5665894271805882
  lightness: 0.7739676956553012
  saturation: 0.587940061930567
  rhythmicContrast: 0.7062413892708719
purpose: []
