name: Alicissimo Admires Plants
favicon: null
layout_spectrum: 0.96877
typography_spectrum: 0.6102295848540962
title: 'Landscape & Botany'
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3B2D0A'
    - '#7D083D'
    - '#BA3971'
    - '#CB9847'
    - '#FFFFC1'
  brandStrength: 0.5665894271805882
  lightness: 0.7739676956553012
  saturation: 0.587940061930567
  rhythmicContrast: 0.5
purpose: []
