name: alicissimo
favicon: null
layout_spectrum: 1
typography_spectrum: 0.6102295848540962
title: 'Landscape & Botany'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#09080e'
    - '#ff8edf'
    - '#5b7fb3'
    - '#821043'
  brandStrength: 0.1875
  lightness: 0.5
  saturation: 0.875
  rhythmicContrast: 1
purpose: []
